### ISSUE TITLE
Max Runs

### ISSUE THREAD

**Issue by renob123** [LateralGs/rallyx_timing_scoring#1]
You can change the number of runs, but pushing the Apply button doesn't result in an immediate change. The old max runs number still shows at the top. Both times I tried changing it, the new max runs number showed up only after the "Internal server not found" error. I suspect the two problems are related, and that hitting the Apply button results in some calculations behind the scenes that ends up crashing the DB. That's all speculation, though.

**Comment by renob123** [comment]
I haven't done timing in a while. Has this been tested IRL? 

Jacob

**Comment by LateralGs** [comment]
Prior to this season I changed how the server recalculates stuff using a separate background task.  This along with a couple other changes fixed the server timeouts/errors we were encountering when doing things like changing the max runs.  We have been updating the max runs at each event without issue this season.

**Comment by renob123** [comment]
That was easy (for me). Thanks. 

Jacob
